# Generated by Django 2.2.1 on 2020-04-28 12:05

import catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=130)),
                ('color', models.CharField(max_length=30)),
                ('weight', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('primary_material', models.CharField(max_length=30)),
                ('finish', models.CharField(max_length=30)),
                ('length', models.IntegerField(max_length=30)),
                ('width', models.IntegerField(max_length=30)),
                ('height', models.IntegerField(max_length=30)),
                ('category', models.CharField(choices=[('Chairs', 'Chairs'), ('Stools', 'Stools'), ('Sofas', 'Sofas'), ('TableTops', 'Table Tops'), ('TableBase', 'Table Base'), ('Booths', 'Booths'), ('PatioFurniture', 'Patio Furniture'), ('Miscellaneous', 'Miscellaneous'), ('Lighting', 'Lighting'), ('StageLighting&Machines', 'Stage Lighting & Machines'), ('Tableware', 'Tableware'), ('Barware', 'Barware'), ('Glassware', 'Glassware'), ('Kitchenware', 'Kitchenware'), ('Equipment', 'Equipment'), ('Machines', 'Machines'), ('Disposables', 'Disposables'), ('DecorativeItems', 'Decorative Items')], max_length=30)),
                ('sub_category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=catalog.models.get_image_filename, verbose_name='Image')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalog.Product')),
            ],
        ),
    ]
