# Generated by Django 2.2.10 on 2020-05-05 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=40)),
                ('vendor_type', models.CharField(choices=[('Manufacturer', 'Manufacturer'), ('Trader', 'Trader'), ('Shop', 'Shop')], max_length=15)),
                ('contact_name', models.CharField(max_length=40)),
                ('wechat', models.IntegerField()),
                ('contact_no', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address_street', models.CharField(blank=True, max_length=80, null=True)),
                ('address_city', models.CharField(blank=True, max_length=30, null=True)),
                ('address_province', models.CharField(blank=True, max_length=30, null=True)),
                ('address_country', models.CharField(blank=True, max_length=20, null=True)),
                ('quality_standards', models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10, null=True)),
                ('previous_exp', models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10, null=True)),
                ('business_till_date', models.CharField(blank=True, max_length=80, null=True)),
                ('commitment_level', models.IntegerField(blank=True, null=True)),
                ('customization', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True)),
                ('payment_terms', models.IntegerField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], null=True)),
                ('observations', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='length',
        ),
        migrations.RemoveField(
            model_name='product',
            name='model',
        ),
        migrations.RemoveField(
            model_name='product',
            name='width',
        ),
        migrations.AddField(
            model_name='product',
            name='cbm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='lead_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='max_price',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='min_price',
            field=models.IntegerField(default=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='model_no',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='moq',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='packing',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='remarks',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='vendor_model_no',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='product',
            name='primary_material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ManyToManyField(to='catalog.SubCategory'),
        ),
        migrations.CreateModel(
            name='PrimaryMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_field_name', models.CharField(blank=True, max_length=30, null=True)),
                ('m_field_value', models.CharField(blank=True, max_length=30, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_field_name', models.CharField(blank=True, max_length=20, null=True)),
                ('d_field_value', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='dimension',
            field=models.ManyToManyField(to='catalog.Dimension'),
        ),
        migrations.AddField(
            model_name='product',
            name='primary_material',
            field=models.ManyToManyField(to='catalog.PrimaryMaterial'),
        ),
    ]
