# Generated by Django 2.2.10 on 2020-05-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20200506_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='finish',
            field=models.CharField(default='finish', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_price',
            field=models.IntegerField(default=100000),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_price',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_no',
            field=models.CharField(default='hstc123', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='moq',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='packing',
            field=models.CharField(default='packing', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='remarks',
            field=models.CharField(default='remarks', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(default='unit', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor_model_no',
            field=models.CharField(default='v123', max_length=30),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='rating',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=10, null=True),
        ),
    ]
