# Generated by Django 2.2.10 on 2020-05-06 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20200506_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dimension',
        ),
        migrations.RemoveField(
            model_name='product',
            name='primary_material',
        ),
    ]
