# Generated by Django 2.2.10 on 2020-05-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20200506_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dimension',
            field=models.ManyToManyField(to='catalog.Dimension'),
        ),
        migrations.AddField(
            model_name='product',
            name='primary_material',
            field=models.ManyToManyField(to='catalog.PrimaryMaterial'),
        ),
    ]
