# Generated by Django 2.2.2 on 2020-05-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20200509_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dimension',
            field=models.ManyToManyField(to='catalog.Dimension'),
        ),
        migrations.AddField(
            model_name='product',
            name='primary_material',
            field=models.ManyToManyField(to='catalog.PrimaryMaterial'),
        ),
    ]
