# Generated by Django 2.2.2 on 2020-05-08 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20200509_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dimension',
        ),
        migrations.RemoveField(
            model_name='product',
            name='primary_material',
        ),
        migrations.AddField(
            model_name='dimension',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='catalog.Product'),
            preserve_default=False,
        ),
    ]
