# Generated by Django 2.2.2 on 2020-05-09 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20200509_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimension',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalog.Product'),
        ),
    ]
