# Generated by Django 2.2.2 on 2020-05-09 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20200509_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimension',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Product'),
        ),
    ]
